//
//  GreetingInteractor.swift
//  MV(X)Petterns
//
//  Created by Alexey Efimov on 21/09/2019.
//  Copyright (c) 2019 Alexey Efimov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetingBusinessLogic {
    func setFullName(request: ShowGreeting.Greeting.Request)
}

protocol GreetingDataStore {
    var fullName: String { get }
}

class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var fullName = ""
    
    // MARK: Do something
    func setFullName(request: ShowGreeting.Greeting.Request) {
        let person = Person(name: "Tim", surname: "Cook")
        fullName = "\(person.name) \(person.surname)"
        let response = ShowGreeting.Greeting.Response(fullName: fullName)
        presenter?.presentGreeting(response: response)
    }
}
